### ISSUE TITLE
 'PoolManager'  not found !!!!!

### ISSUE THREAD

**Issue by manik987** [sethblack/python-seo-analyzer#67]
**Describe the bug**
After writing the command "python analyzer.py https://www.sethserver.com/ -f html > results.html" it got the error of pool manager not found.
how can i run this project 

**Expected behavior**
to run the website and show answer in result.html 

**Screenshots**
whole error
______________________________________________________________________________________________________________

Traceback (most recent call last):
  File "analyzer.py", line 5, in <module>
    from seoanalyzer.website import Website
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\__init__.py", line 3, in <module>
    from .analyzer import analyze
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\analyzer.py", line 5, in <module>
    from seoanalyzer.website import Website
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\website.py", line 8, in <module>
    from seoanalyzer.http import http
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\http.py", line 2, in <module>
    import urllib3
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 203, in load_module
    mod = mod._resolve()
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 82, in _import_module
    __import__(name)
  File "F:\python-seo-analyzer-master (2)\python-seo-analyzer-master\seoanalyzer\http.py", line 18, in <module>
    http = Http()
  File "F:\python-seo-analyzer-master (2)\python-seo-analyzer-master\seoanalyzer\http.py", line 8, in __init__
    self.http = urllib3.PoolManager(
AttributeError: module 'urllib3' has no attribute 'PoolManager'

*Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [microsoft edge, chrome]
 - Version [4.0.2]
 - 
**Additional context**

**Comment by sethblack** [comment]
Roger that. Looks like on Windows we can't grab PoolManager from the urllib3 it needs to be imported.

**Comment by manik987** [comment]
how can i do that please help

**Comment by manik987** [comment]
still showing this error ?

python analyzer.py https://www.sethserver.com/ -f html > results.html
Traceback (most recent call last):
File "analyzer.py", line 5, in
from seoanalyzer.website import Website
File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer_init_.py", line 3, in
from .analyzer import analyze
File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\analyzer.py", line 5, in
from seoanalyzer.website import Website
File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\website.py", line 8, in
from seoanalyzer.http import http
File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\http.py", line 2, in
import urllib3
File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3_init_.py", line 8, in
from .connectionpool import (
File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 11, in
from .exceptions import (
File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\exceptions.py", line 2, in
from .packages.six.moves.http_client import (
File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 203, in load_module
mod = mod._resolve()
File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 115, in _resolve
return _import_module(self.mod)
File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 82, in import_module
import(name)
File "C:\Users\Manik Malhotra\Downloads\python-seo-analyzer-master (5)\python-seo-analyzer-master\seoanalyzer\http.py", line 2, in
from urllib3 import PoolManager
ImportError: cannot import name 'PoolManager' from 'urllib3' (C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3_init.py)

**Comment by henri9813** [comment]
Is it fixed with https://github.com/sethblack/python-seo-analyzer/pull/68 ?

**Comment by FlyingSpringrol** [comment]
@henri9813 nope, was still broken on my comp (August 21, 2021). 
Anaconda installation of python 3.9, Big Sur 11.4. 

@manik987 I solved this error by just using a virtual env though. https://docs.python.org/3/tutorial/venv.html .

**Comment by henri9813** [comment]
Oki, you can use docker image if you want ( i don't know if it's has been released or not, but i provide one for this  in https://github.com/sethblack/python-seo-analyzer/pull/71 )
